name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cartoonizer-api:latest  # Replace placeholders

      - name: Build and push Docker image (multi-arch)  # Optional for multi-architecture support
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cartoonizer-api:latest-multiarch  # Replace placeholders
          platforms: linux/amd64,linux/arm64  # Example platforms (adjust as needed)
